[project]
name = "universities-scrapy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scrapy-splash>=0.9.0",
    "scrapy>=2.11.2",
]

[dependency-groups]
dev = [
    "six>=1.16.0",
]
